# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinpayments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardToken',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('environment', models.CharField(help_text='The name of the Pin environment to use, eg test or live.', max_length=25, db_index=True, blank=True)),
                ('token', models.CharField(help_text='Generated by Card API or Customers API', max_length=100, verbose_name='Token')),
                ('scheme', models.CharField(choices=[('master', 'Mastercard'), ('visa', 'Visa')], max_length=20, blank=True, help_text='Determined automatically by Pin', null=True, verbose_name='Card type')),
                ('name', models.CharField(help_text='Cleansed by Pin API', max_length=100, null=True, verbose_name='Cardholder name', blank=True)),
                ('display_number', models.CharField(help_text='Cleansed by Pin API', max_length=100, null=True, verbose_name='Card display number', blank=True)),
                ('expiry_month', models.IntegerField(default=None, null=True, verbose_name='Card expiry month', blank=True)),
                ('expiry_year', models.IntegerField(default=None, null=True, verbose_name='Card expiry year', blank=True)),
                ('address_line1', models.CharField(help_text='Address entered by customer to process this transaction', max_length=100, null=True, verbose_name='Cardholder street address', blank=True)),
                ('address_line2', models.CharField(max_length=100, null=True, verbose_name='Cardholder street address Line 2', blank=True)),
                ('address_city', models.CharField(max_length=100, null=True, verbose_name='Cardholder city', blank=True)),
                ('address_state', models.CharField(max_length=100, null=True, verbose_name='Cardholder state', blank=True)),
                ('address_postcode', models.CharField(max_length=100, null=True, verbose_name='Cardholder postal / ZIP code', blank=True)),
                ('address_country', models.CharField(max_length=100, null=True, verbose_name='Cardholder country', blank=True)),
                ('primary', models.NullBooleanField(default=False, verbose_name="Customer's primary card")),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='customertoken',
            name='cards',
            field=models.ManyToManyField(to='pinpayments.CardToken'),
            preserve_default=True,
        ),
    ]
